#!/bin/sh

set -e

dir="$(git rev-parse --git-dir)"
tagfile="$dir/$$.tags"

trap 'rm -f "$tagfile"' EXIT

git ls-files | \
  ctags --tag-relative -L - -f "$tagfile" --languages=-javascript,sql

mv -f "$tagfile" "$dir/tags"
